# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4


params:

  background: "images/shades-of-blue-4k-cw.jpg"

  customMenus:
  - name: Notes
    url: https://hossainemruz.gitbook.io/notes/
    hideFromNavbar: false
    showOnFooter: true

  enableTOC: true
  enableBlogPost: true

  markup:
    tableOfContents:
      startLevel: 2
      endLevel: 6
      ordered: false

  newsletter:
    enable: false